// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OmsLoan.Domain;

#nullable disable

namespace OmsLoan.Domain.Migrations
{
    [DbContext(typeof(OmsLoanDbContext))]
    partial class OmsLoanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OmsLoan.Domain.ExtractedField", b =>
                {
                    b.Property<int>("ExtractedFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtractedFieldId"));

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime?>("CorrectedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("CorrectedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CorrectedValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtractionId")
                        .HasColumnType("int");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("ExtractedFieldId");

                    b.HasIndex("ExtractionId", "FieldName");

                    b.ToTable("ExtractedFields", (string)null);
                });

            modelBuilder.Entity("OmsLoan.Domain.Extraction", b =>
                {
                    b.Property<int>("ExtractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtractionId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("NoticeId")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExtractionId");

                    b.HasIndex("NoticeId", "IsCurrent");

                    b.ToTable("Extractions", (string)null);
                });

            modelBuilder.Entity("OmsLoan.Domain.Notice", b =>
                {
                    b.Property<int>("NoticeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoticeId"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("EmailMessageId")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("varchar(512)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sender")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("NoticeId");

                    b.HasIndex("EmailMessageId")
                        .IsUnique()
                        .HasFilter("[EmailMessageId] IS NOT NULL");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.ToTable("Notices", (string)null);
                });

            modelBuilder.Entity("OmsLoan.Domain.ExtractedField", b =>
                {
                    b.HasOne("OmsLoan.Domain.Extraction", "Extraction")
                        .WithMany("Fields")
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Extraction");
                });

            modelBuilder.Entity("OmsLoan.Domain.Extraction", b =>
                {
                    b.HasOne("OmsLoan.Domain.Notice", "Notice")
                        .WithMany("Extractions")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("OmsLoan.Domain.Extraction", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("OmsLoan.Domain.Notice", b =>
                {
                    b.Navigation("Extractions");
                });
#pragma warning restore 612, 618
        }
    }
}
