// <auto-generated />
using System;
using LoanDbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanDbModel.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20250408172009_3rdMigration")]
    partial class _3rdMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanDbModel.Accrual", b =>
                {
                    b.Property<int>("AccrualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccrualId"));

                    b.Property<string>("AccrualCode")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasComputedColumnSql("'ACR' + RIGHT('00000' + CAST([AccrualId] AS VARCHAR(5)), 5)", true);

                    b.Property<string>("Act")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BankRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateOnly>("FromDate")
                        .HasColumnType("date");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Notional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ParentAccrualId")
                        .HasColumnType("int");

                    b.Property<decimal>("Spread")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("ToDate")
                        .HasColumnType("date");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccrualId");

                    b.HasIndex("AccrualCode")
                        .IsUnique();

                    b.HasIndex("ParentAccrualId");

                    b.HasIndex("TradeId");

                    b.ToTable("Accruals", "loans");
                });

            modelBuilder.Entity("LoanDbModel.Blotter", b =>
                {
                    b.Property<int>("BlotterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlotterId"));

                    b.Property<string>("BuySell")
                        .IsRequired()
                        .HasColumnType("varchar(1)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("CounterPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GlobalCommitment")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Notional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Spread")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ticket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeAcct")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BlotterId");

                    b.HasIndex("CounterPartyId");

                    b.ToTable("Blotters", "loans");
                });

            modelBuilder.Entity("LoanDbModel.CounterParty", b =>
                {
                    b.Property<int>("CounterPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounterPartyId"));

                    b.Property<string>("CounterPartyCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CounterPartyName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("DomicileCountry")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CounterPartyId");

                    b.ToTable("CounterParties", "loans");
                });

            modelBuilder.Entity("LoanDbModel.Paydown", b =>
                {
                    b.Property<int>("PaydownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaydownId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notice")
                        .HasColumnType("varchar(500)");

                    b.Property<decimal?>("ProRataShare")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("PaydownId");

                    b.HasIndex("TradeId");

                    b.ToTable("Paydowns", "loans");
                });

            modelBuilder.Entity("LoanDbModel.SettledPaydownCashWire", b =>
                {
                    b.Property<int>("SettledPaydownCashWireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettledPaydownCashWireId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaydownId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("SettledPaydownCashWireId");

                    b.HasIndex("PaydownId");

                    b.ToTable("SettledPaydownCashWires", "loans");
                });

            modelBuilder.Entity("LoanDbModel.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<decimal>("AdditionalCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BuySell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CommitmentReduction")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CounterPartyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DelayCompensation")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EconomicBenefit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FeesCosts")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GlobalCommitment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestReceived")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsSettled")
                        .HasColumnType("bit");

                    b.Property<decimal>("Notional")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Spread")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Strategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TermUnfundedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeAcct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TradeId");

                    b.HasIndex("CounterPartyId");

                    b.ToTable("Trades", "loans");
                });

            modelBuilder.Entity("LoanDbModel.TradeDocument", b =>
                {
                    b.Property<int>("TradeDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeDocumentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(500)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TradeDocumentId");

                    b.HasIndex("TradeId");

                    b.ToTable("TradeDocuments", "loans");
                });

            modelBuilder.Entity("LoanDbModel.Accrual", b =>
                {
                    b.HasOne("LoanDbModel.Accrual", "ParentAccrual")
                        .WithMany("ChildAccruals")
                        .HasForeignKey("ParentAccrualId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("LoanDbModel.Trade", "Trade")
                        .WithMany("Accruals")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ParentAccrual");

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("LoanDbModel.Blotter", b =>
                {
                    b.HasOne("LoanDbModel.CounterParty", "CounterParty")
                        .WithMany("Blotters")
                        .HasForeignKey("CounterPartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CounterParty");
                });

            modelBuilder.Entity("LoanDbModel.Paydown", b =>
                {
                    b.HasOne("LoanDbModel.Trade", "Trade")
                        .WithMany("Paydowns")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("LoanDbModel.SettledPaydownCashWire", b =>
                {
                    b.HasOne("LoanDbModel.Paydown", "Paydown")
                        .WithMany("SettledPaydownCashWires")
                        .HasForeignKey("PaydownId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Paydown");
                });

            modelBuilder.Entity("LoanDbModel.Trade", b =>
                {
                    b.HasOne("LoanDbModel.CounterParty", "CounterParty")
                        .WithMany("Trades")
                        .HasForeignKey("CounterPartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CounterParty");
                });

            modelBuilder.Entity("LoanDbModel.TradeDocument", b =>
                {
                    b.HasOne("LoanDbModel.Trade", "Trade")
                        .WithMany("TradeDocuments")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("LoanDbModel.Accrual", b =>
                {
                    b.Navigation("ChildAccruals");
                });

            modelBuilder.Entity("LoanDbModel.CounterParty", b =>
                {
                    b.Navigation("Blotters");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("LoanDbModel.Paydown", b =>
                {
                    b.Navigation("SettledPaydownCashWires");
                });

            modelBuilder.Entity("LoanDbModel.Trade", b =>
                {
                    b.Navigation("Accruals");

                    b.Navigation("Paydowns");

                    b.Navigation("TradeDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
