// <auto-generated />
using System;
using LoanDbModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LoanDbModel.Migrations
{
    [DbContext(typeof(LoanDbContext))]
    [Migration("20250331233400_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LoanDbModel.Accrual", b =>
                {
                    b.Property<int>("AccrualId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AccrualId"));

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AccrualId");

                    b.ToTable("Accruals");
                });

            modelBuilder.Entity("LoanDbModel.Blotter", b =>
                {
                    b.Property<int>("BlotterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlotterId"));

                    b.Property<string>("BuySell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CUSIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CounterPartyId")
                        .HasColumnType("int");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GlobalCommitment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Notional")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Spread")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ticket")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeAcct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BlotterId");

                    b.HasIndex("CounterPartyId");

                    b.ToTable("Blotters", "loan");
                });

            modelBuilder.Entity("LoanDbModel.CounterParty", b =>
                {
                    b.Property<int>("CounterPartyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CounterPartyId"));

                    b.Property<string>("CounterPartyCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CounterPartyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DomicileCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CounterPartyId");

                    b.ToTable("CounterParties", "loan");
                });

            modelBuilder.Entity("LoanDbModel.Paydown", b =>
                {
                    b.Property<int>("PaydownId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaydownId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProRataShare")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TradeId")
                        .HasColumnType("int");

                    b.HasKey("PaydownId");

                    b.HasIndex("TradeId");

                    b.ToTable("Paydowns", "loan");
                });

            modelBuilder.Entity("LoanDbModel.SettledPaydownCashWire", b =>
                {
                    b.Property<int>("SettledPaydownCashWireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettledPaydownCashWireId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaydownId")
                        .HasColumnType("int");

                    b.HasKey("SettledPaydownCashWireId");

                    b.HasIndex("PaydownId");

                    b.ToTable("SettledPaydownCashWires", "loan");
                });

            modelBuilder.Entity("LoanDbModel.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TradeId"));

                    b.Property<decimal>("AdditionalCredit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BuySell")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BuySell");

                    b.Property<string>("CUSIP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CommitmentReduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CounterPartyId")
                        .HasColumnType("int");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DelayCompensation")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("EconomicBenefit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FeesCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GlobalCommitment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("InterestReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Notional")
                        .HasColumnType("money");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SettlementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Spread")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubStrategy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TermUnfundedAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradeAcct")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("TradeId");

                    b.HasIndex("CounterPartyId");

                    b.ToTable("Trades", "loan");
                });

            modelBuilder.Entity("LoanDbModel.Blotter", b =>
                {
                    b.HasOne("LoanDbModel.CounterParty", "CounterParty")
                        .WithMany("Blotters")
                        .HasForeignKey("CounterPartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CounterParty");
                });

            modelBuilder.Entity("LoanDbModel.Paydown", b =>
                {
                    b.HasOne("LoanDbModel.Trade", "Trade")
                        .WithMany("Paydowns")
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Trade");
                });

            modelBuilder.Entity("LoanDbModel.SettledPaydownCashWire", b =>
                {
                    b.HasOne("LoanDbModel.Paydown", "Paydown")
                        .WithMany("SettledPaydownCashWires")
                        .HasForeignKey("PaydownId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Paydown");
                });

            modelBuilder.Entity("LoanDbModel.Trade", b =>
                {
                    b.HasOne("LoanDbModel.CounterParty", "CounterParty")
                        .WithMany("Trades")
                        .HasForeignKey("CounterPartyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CounterParty");
                });

            modelBuilder.Entity("LoanDbModel.CounterParty", b =>
                {
                    b.Navigation("Blotters");

                    b.Navigation("Trades");
                });

            modelBuilder.Entity("LoanDbModel.Paydown", b =>
                {
                    b.Navigation("SettledPaydownCashWires");
                });

            modelBuilder.Entity("LoanDbModel.Trade", b =>
                {
                    b.Navigation("Paydowns");
                });
#pragma warning restore 612, 618
        }
    }
}
