// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OmsLoan.Domain;

#nullable disable

namespace OmsLoan.Data.Postgres.Migrations
{
    [DbContext(typeof(OmsLoanDbContext))]
    [Migration("20260911181828_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OmsLoan.Domain.ExtractedField", b =>
                {
                    b.Property<int>("ExtractedFieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExtractedFieldId"));

                    b.Property<decimal?>("Confidence")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime?>("CorrectedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CorrectedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("CorrectedValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTime?>("DateValue")
                        .HasColumnType("date");

                    b.Property<int>("ExtractionId")
                        .HasColumnType("integer");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("RawValue")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.HasKey("ExtractedFieldId");

                    b.HasIndex("ExtractionId", "FieldName");

                    b.ToTable("ExtractedFields", (string)null);
                });

            modelBuilder.Entity("OmsLoan.Domain.Extraction", b =>
                {
                    b.Property<int>("ExtractionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExtractionId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("boolean");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("NoticeId")
                        .HasColumnType("integer");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("RawJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ExtractionId");

                    b.HasIndex("NoticeId", "IsCurrent");

                    b.ToTable("Extractions", (string)null);
                });

            modelBuilder.Entity("OmsLoan.Domain.Notice", b =>
                {
                    b.Property<int>("NoticeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoticeId"));

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("EmailMessageId")
                        .HasMaxLength(512)
                        .IsUnicode(false)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sender")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<DateTime?>("SentAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character(64)")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("NoticeId");

                    b.HasIndex("EmailMessageId")
                        .HasFilter("\"EmailMessageId\" IS NOT NULL");

                    b.HasIndex("Sha256");

                    b.ToTable("Notices", (string)null);
                });

            modelBuilder.Entity("OmsLoan.Domain.ExtractedField", b =>
                {
                    b.HasOne("OmsLoan.Domain.Extraction", "Extraction")
                        .WithMany("Fields")
                        .HasForeignKey("ExtractionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Extraction");
                });

            modelBuilder.Entity("OmsLoan.Domain.Extraction", b =>
                {
                    b.HasOne("OmsLoan.Domain.Notice", "Notice")
                        .WithMany("Extractions")
                        .HasForeignKey("NoticeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Notice");
                });

            modelBuilder.Entity("OmsLoan.Domain.Extraction", b =>
                {
                    b.Navigation("Fields");
                });

            modelBuilder.Entity("OmsLoan.Domain.Notice", b =>
                {
                    b.Navigation("Extractions");
                });
#pragma warning restore 612, 618
        }
    }
}
